# Generated by Django 5.2.1 on 2025-05-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_invoice'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credit_cards.invoice', verbose_name='Invoice'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
