# Generated by Django 5.2.1 on 2025-05-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_created_at_profile_deactivation_scheduled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Initial Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.profile')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'constraints': [models.UniqueConstraint(fields=('name', 'profile'), name='unique_bank_account_name_per_profile')],
            },
        ),
    ]
