# Generated by Django 5.2.1 on 2025-05-27 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_alter_bankaccount_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Initial balance cannot be negative')], verbose_name='Initial Balance'),
        ),
    ]
