# Generated by Django 5.2.1 on 2025-05-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_alter_bankaccount_initial_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
    ]
