# Generated by Django 5.2.1 on 2025-05-28 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_profile_created_at_alter_profile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color_hex', models.CharField(default='#000000', max_length=7, verbose_name='Goal Color')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Initial balance cannot be negative')], verbose_name='Initial Balance')),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Goal amount cannot be negative')], verbose_name='Goal Amount')),
                ('target_at', models.DateField(verbose_name='Target At')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Completed At')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.profile')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='GoalDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Deposit amount cannot be negative')], verbose_name='Deposit Amount')),
                ('deposit_at', models.DateField(verbose_name='Deposit At')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='goals.goal')),
            ],
            options={
                'verbose_name': 'Goal Deposit',
                'verbose_name_plural': 'Goal Deposits',
            },
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_goal_name_per_profile', violation_error_message='A goal with this name already exists for this profile'),
        ),
    ]
