# Generated by Django 5.2.1 on 2025-05-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaldeposit',
            name='deposit_at',
            field=models.DateField(auto_now_add=True, verbose_name='Deposit At'),
        ),
    ]
