# Generated by Django 5.2.1 on 2025-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goaldeposit_deposit_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaldeposit',
            name='deposit_at',
            field=models.DateField(verbose_name='Deposit At'),
        ),
        migrations.AlterField(
            model_name='goaldeposit',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
