# Generated by Django 5.2.1 on 2025-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField(help_text='The ID of the profile that was targeted by the action (the object of the change)', verbose_name='Profile ID')),
                ('actor_user_id', models.UUIDField(blank=True, help_text='The ID of the user who performed the action (the actor). Null if it is a system action.', null=True, verbose_name='Actor User ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Action Time')),
                ('action_type', models.CharField(max_length=10, verbose_name='Action Type')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Entity Type')),
                ('entity_id', models.CharField(max_length=36, verbose_name='Entity ID')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('correlation_id', models.UUIDField(blank=True, null=True, verbose_name='Correlation ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Service Name')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-action_time'],
            },
        ),
    ]
