# Generated by Django 5.2.1 on 2025-07-15 23:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Keycloak sub (subject) identifier', primary_key=True, serialize=False, verbose_name='User ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('is_deactivated', models.BooleanField(default=False)),
                ('deactivation_scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['email'],
            },
        ),
    ]
