# Generated by Django 5.2.1 on 2025-05-28 01:27

import django.core.validators
import django.db.models.deletion
import poupeai_finance_service.credit_cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_profile_created_at_alter_profile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Credit limit cannot be negative.')], verbose_name='Credit Limit')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Info')),
                ('closing_day', models.SmallIntegerField(validators=[poupeai_finance_service.credit_cards.validators.validate_day], verbose_name='Closing Day')),
                ('due_day', models.SmallIntegerField(validators=[poupeai_finance_service.credit_cards.validators.validate_day], verbose_name='Due Day')),
                ('brand', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('ELO', 'Elo'), ('HIPERCARD', 'Hipercard')], max_length=20, verbose_name='Brand')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='users.profile')),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_credit_card_name_per_profile', violation_error_message='A credit card with this name already exists for this profile.')],
            },
        ),
    ]
