# Generated by Django 5.2.1 on 2025-05-30 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('month', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(12)], verbose_name='Month')),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Year')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount Paid')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='credit_cards.creditcard', verbose_name='Credit Card')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-year', '-month'],
                'unique_together': {('credit_card', 'month', 'year')},
            },
        ),
    ]
