# Generated by Django 5.2.1 on 2025-07-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='overdue_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Overdue Notification Sent'),
        ),
    ]
