# Generated by Django 5.2.1 on 2025-07-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_invoice_overdue_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_soon_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Due Soon Notification Sent'),
        ),
    ]
