from enum import Enum

class EventType(str, Enum):
    REQUEST_COMPLETED = "REQUEST_COMPLETED"

    # --- Eventos do App 'Profiles' ---
    PROFILE_CREATED = "PROFILE_CREATED"
    PROFILE_UPDATED = "PROFILE_UPDATED"
    PROFILE_DELETED = "PROFILE_DELETED"
    PROFILE_DEACTIVATED = "PROFILE_DEACTIVATED"
    PROFILE_DEACTIVATION_FAILED = "PROFILE_DEACTIVATION_FAILED"
    PROFILE_REACTIVATED = "PROFILE_REACTIVATED"
    PROFILE_REACTIVATION_FAILED = "PROFILE_REACTIVATION_FAILED"

    # --- Eventos da Task de 'Profiles' ---
    EXPIRED_PROFILES_CLEANUP_SKIPPED = "EXPIRED_PROFILES_CLEANUP_SKIPPED"
    EXPIRED_PROFILES_CLEANUP_COMPLETED = "EXPIRED_PROFILES_CLEANUP_COMPLETED"
    PROFILE_DELETION_STARTED = "PROFILE_DELETION_STARTED"
    PROFILE_DELETION_SUCCESSFUL = "PROFILE_DELETION_SUCCESSFUL"
    PROFILE_DELETION_FAILED = "PROFILE_DELETION_FAILED"
    KEYCLOAK_USER_DELETION_FAILED = "KEYCLOAK_USER_DELETION_FAILED"

    # Eventos dos outros apps ...
    # Ex: TRANSACTION_CREATED = "TRANSACTION_CREATED"