from enum import Enum

class EventType(str, Enum):
    REQUEST_COMPLETED = "REQUEST_COMPLETED"

    # --- Eventos do App 'Profiles' ---
    PROFILE_CREATED = "PROFILE_CREATED"
    PROFILE_UPDATED = "PROFILE_UPDATED"
    PROFILE_DELETED = "PROFILE_DELETED"
    PROFILE_DEACTIVATED = "PROFILE_DEACTIVATED"
    PROFILE_DEACTIVATION_FAILED = "PROFILE_DEACTIVATION_FAILED"
    PROFILE_REACTIVATED = "PROFILE_REACTIVATED"
    PROFILE_REACTIVATION_FAILED = "PROFILE_REACTIVATION_FAILED"

    # --- Eventos da Task de 'Profiles' ---
    EXPIRED_PROFILES_CLEANUP_SKIPPED = "EXPIRED_PROFILES_CLEANUP_SKIPPED"
    EXPIRED_PROFILES_CLEANUP_COMPLETED = "EXPIRED_PROFILES_CLEANUP_COMPLETED"
    PROFILE_DELETION_STARTED = "PROFILE_DELETION_STARTED"
    PROFILE_DELETION_SUCCESSFUL = "PROFILE_DELETION_SUCCESSFUL"
    PROFILE_DELETION_FAILED = "PROFILE_DELETION_FAILED"
    KEYCLOAK_USER_DELETION_FAILED = "KEYCLOAK_USER_DELETION_FAILED"

    # --- Eventos de Autenticação ---
    AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    TOKEN_VALIDATION_FAILED = "TOKEN_VALIDATION_FAILED"
    JWKS_FETCH_FAILED = "JWKS_FETCH_FAILED"
    PROFILE_CREATED_FROM_TOKEN = "PROFILE_CREATED_FROM_TOKEN"
    PROFILE_UPDATED_FROM_TOKEN = "PROFILE_UPDATED_FROM_TOKEN"
    DEFAULT_BANK_ACCOUNT_CREATION_FAILED = "DEFAULT_BANK_ACCOUNT_CREATION_FAILED"

    # --- Eventos do App 'Transactions' ---
    TRANSACTION_CREATED = "TRANSACTION_CREATED"
    TRANSACTION_UPDATED = "TRANSACTION_UPDATED"
    TRANSACTION_DELETED = "TRANSACTION_DELETED"
    TRANSACTION_CREATION_FAILED = "TRANSACTION_CREATION_FAILED"
    TRANSACTION_UPDATE_FAILED = "TRANSACTION_UPDATE_FAILED"
    TRANSACTION_DELETION_FAILED = "TRANSACTION_DELETION_FAILED"