from enum import Enum

class EventType(str, Enum):
    REQUEST_COMPLETED = "REQUEST_COMPLETED"

    # --- Eventos do App 'Profiles' ---
    PROFILE_CREATED = "PROFILE_CREATED"
    PROFILE_UPDATED = "PROFILE_UPDATED"
    PROFILE_DELETED = "PROFILE_DELETED"
    PROFILE_DEACTIVATED = "PROFILE_DEACTIVATED"
    PROFILE_DEACTIVATION_FAILED = "PROFILE_DEACTIVATION_FAILED"
    PROFILE_REACTIVATED = "PROFILE_REACTIVATED"
    PROFILE_REACTIVATION_FAILED = "PROFILE_REACTIVATION_FAILED"

    # --- Eventos da Task de 'Profiles' ---
    EXPIRED_PROFILES_CLEANUP_SKIPPED = "EXPIRED_PROFILES_CLEANUP_SKIPPED"
    EXPIRED_PROFILES_CLEANUP_COMPLETED = "EXPIRED_PROFILES_CLEANUP_COMPLETED"
    PROFILE_DELETION_STARTED = "PROFILE_DELETION_STARTED"
    PROFILE_DELETION_SUCCESSFUL = "PROFILE_DELETION_SUCCESSFUL"
    PROFILE_DELETION_FAILED = "PROFILE_DELETION_FAILED"
    KEYCLOAK_USER_DELETION_FAILED = "KEYCLOAK_USER_DELETION_FAILED"

    # --- Eventos de Autenticação ---
    AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    TOKEN_VALIDATION_FAILED = "TOKEN_VALIDATION_FAILED"
    JWKS_FETCH_FAILED = "JWKS_FETCH_FAILED"
    PROFILE_CREATED_FROM_TOKEN = "PROFILE_CREATED_FROM_TOKEN"
    PROFILE_UPDATED_FROM_TOKEN = "PROFILE_UPDATED_FROM_TOKEN"
    DEFAULT_BANK_ACCOUNT_CREATION_FAILED = "DEFAULT_BANK_ACCOUNT_CREATION_FAILED"

    # --- Eventos do App 'Transactions' ---
    TRANSACTION_CREATED = "TRANSACTION_CREATED"
    TRANSACTION_UPDATED = "TRANSACTION_UPDATED"
    TRANSACTION_DELETED = "TRANSACTION_DELETED"
    TRANSACTION_CREATION_FAILED = "TRANSACTION_CREATION_FAILED"
    TRANSACTION_UPDATE_FAILED = "TRANSACTION_UPDATE_FAILED"
    TRANSACTION_DELETION_FAILED = "TRANSACTION_DELETION_FAILED"

    # --- Eventos do App 'Goals' ---
    GOAL_CREATED = "GOAL_CREATED"
    GOAL_UPDATED = "GOAL_UPDATED"
    GOAL_DELETED = "GOAL_DELETED"
    GOAL_COMPLETED = "GOAL_COMPLETED"
    GOAL_DEPOSIT_MADE = "GOAL_DEPOSIT_MADE"
    
    # Eventos de Falha
    GOAL_CREATION_FAILED = "GOAL_CREATION_FAILED"
    GOAL_UPDATE_FAILED = "GOAL_UPDATE_FAILED"
    GOAL_DELETION_FAILED = "GOAL_DELETION_FAILED"
    GOAL_DEPOSIT_FAILED = "GOAL_DEPOSIT_FAILED"

    # --- Eventos do App 'Credit Cards' ---
    CREDIT_CARD_CREATED = "CREDIT_CARD_CREATED"
    CREDIT_CARD_UPDATED = "CREDIT_CARD_UPDATED"
    CREDIT_CARD_DELETED = "CREDIT_CARD_DELETED"
    CREDIT_CARD_CREATION_FAILED = "CREDIT_CARD_CREATION_FAILED"
    CREDIT_CARD_UPDATE_FAILED = "CREDIT_CARD_UPDATE_FAILED"
    CREDIT_CARD_DELETION_FAILED = "CREDIT_CARD_DELETION_FAILED"

    # --- Eventos de 'Invoices' ---
    INVOICE_PAID = "INVOICE_PAID"
    INVOICE_REOPENED = "INVOICE_REOPENED"
    INVOICE_DELETED = "INVOICE_DELETED"
    INVOICE_PAYMENT_FAILED = "INVOICE_PAYMENT_FAILED"
    INVOICE_REOPEN_FAILED = "INVOICE_REOPEN_FAILED"
    INVOICE_DELETION_FAILED = "INVOICE_DELETION_FAILED"

    # --- Eventos de Interação com Keycloak ---
    KEYCLOAK_ADMIN_CLIENT_INIT_FAILED = "KEYCLOAK_ADMIN_CLIENT_INIT_FAILED"
    KEYCLOAK_USER_DELETION_SUCCESS = "KEYCLOAK_USER_DELETION_SUCCESS"
    KEYCLOAK_USER_DELETION_NOT_FOUND = "KEYCLOAK_USER_DELETION_NOT_FOUND"
    KEYCLOAK_USER_DELETION_ERROR = "KEYCLOAK_USER_DELETION_ERROR"

    # --- Eventos do App 'Categories' ---
    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_UPDATED = "CATEGORY_UPDATED"
    CATEGORY_DELETED = "CATEGORY_DELETED"
    CATEGORY_CREATION_FAILED = "CATEGORY_CREATION_FAILED"
    CATEGORY_UPDATE_FAILED = "CATEGORY_UPDATE_FAILED"
    CATEGORY_DELETION_FAILED = "CATEGORY_DELETION_FAILED"

    # --- Eventos do App 'Budgets' ---
    BUDGET_CREATED = "BUDGET_CREATED"
    BUDGET_UPDATED = "BUDGET_UPDATED"
    BUDGET_DELETED = "BUDGET_DELETED"
    BUDGET_CREATION_FAILED = "BUDGET_CREATION_FAILED"
    BUDGET_UPDATE_FAILED = "BUDGET_UPDATE_FAILED"
    BUDGET_DELETION_FAILED = "BUDGET_DELETION_FAILED"