#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

echo "Verificando a necessidade de criar um superusuário..."
python << END
import os
import django
from django.contrib.auth import get_user_model

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.production')
django.setup()

User = get_user_model()

username = os.getenv('DJANGO_SUPERUSER_USERNAME')
email = os.getenv('DJANGO_SUPERUSER_EMAIL')
password = os.getenv('DJANGO_SUPERUSER_PASSWORD')

if all([username, email, password]):
    if not User.objects.filter(username=username).exists():
        print(f"Criando superusuário '{username}'...")
        User.objects.create_superuser(username=username, email=email, password=password)
        print("Superusuário criado com sucesso.")
    else:
        print(f"Superusuário '{username}' já existe. Nenhuma ação necessária.")
else:
    print("Variáveis de ambiente do superusuário não configuradas. Pulando a criação.")

END

echo "Iniciando o servidor Gunicorn..."
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
