# Generated by Django 5.2.1 on 2025-05-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_profile_created_at_alter_profile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=30, verbose_name='Category Name')),
                ('color_hex', models.CharField(default='#000000', max_length=7, verbose_name='Category Color')),
                ('type', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita')], max_length=7, verbose_name='Category Type')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='User')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
