name: CI/CD para Poupe.AI Finance Service

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: franciscopaulinoq/poupeai-finance-service
  INFRA_DIR: /home/deployer/poupeai-infra
  COMPOSE_SERVICE_NAME: finances-service

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./compose/local/django/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "--- Login no Docker Hub no servidor ---"
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            echo "--- Navegando para o diretório de infra ---"
            cd ${{ env.INFRA_DIR }}

            echo "--- Atualizando a imagem mais recente do serviço ---"
            docker compose -f docker-compose-production.yml pull ${{ env.COMPOSE_SERVICE_NAME }}

            echo "--- Recriando o contêiner do serviço com a nova imagem ---"
            docker compose -f docker-compose-production.yml up -d --force-recreate --no-deps ${{ env.COMPOSE_SERVICE_NAME }}

            echo "--- Limpando imagens Docker antigas e não utilizadas ---"
            docker image prune -af

            echo "--- Deploy finalizado com sucesso! ---"